/**
 * fundeb-comercial-pdf.ts
 *
 * Playwright-based PDF engine for the FUNDEB commercial premium report.
 * Takes a full HTML string (generated by fundeb-comercial-template.ts),
 * captures each 16:9 slide at 1920×1080, and assembles a landscape PDF.
 *
 * This is the server-side pipeline that guarantees 100% visual fidelity
 * with the HTML presentation.
 */

import { chromium, type Browser, type Page } from "playwright";

const VP_WIDTH = 1920;
const VP_HEIGHT = 1080;

/**
 * Generate a landscape PDF from an HTML slide presentation.
 *
 * @param htmlContent - Complete self-contained HTML string with all 18 slides
 * @param municipioSlug - Slugified municipality name for the filename
 * @returns Buffer of the PDF and suggested filename
 */
export async function generateComercialPremiumPdf(
  htmlContent: string,
  municipioSlug: string = "municipio",
): Promise<{ pdfBuffer: Buffer; filename: string }> {
  let browser: Browser | null = null;

  try {
    browser = await chromium.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    // ── Step 1: Capture each slide as a screenshot ──────────────────
    const capturePage = await browser.newPage({
      viewport: { width: VP_WIDTH, height: VP_HEIGHT },
    });

    await capturePage.setContent(htmlContent, { waitUntil: "networkidle" });
    await capturePage.evaluate(() => (document as any).fonts?.ready);
    await capturePage.waitForTimeout(1500);

    // Force all animations off globally
    await capturePage.evaluate(() => {
      const style = document.createElement("style");
      style.textContent = `
        .reveal, .reveal-left, .reveal-scale, .reveal-blur,
        [class*="reveal"] {
          opacity: 1 !important;
          transform: none !important;
          transition: none !important;
          visibility: visible !important;
          filter: none !important;
          animation: none !important;
        }
        .slide .reveal, .slide .reveal-left {
          opacity: 1 !important;
          transform: none !important;
          transition: none !important;
        }
        .bar-fill {
          animation: none !important;
          transition: none !important;
        }
        * {
          transition-delay: 0s !important;
          animation-delay: 0s !important;
        }
      `;
      document.head.appendChild(style);
    });

    const slideCount = await capturePage.evaluate(
      () => document.querySelectorAll(".slide").length,
    );

    const screenshots: Buffer[] = [];

    for (let i = 0; i < slideCount; i++) {
      await capturePage.evaluate((index: number) => {
        const slides = document.querySelectorAll(".slide");
        slides.forEach((slide, idx) => {
          const el = slide as HTMLElement;
          if (idx === index) {
            el.style.display = "";
            el.style.opacity = "1";
            el.style.visibility = "visible";
            el.style.position = "relative";
            el.style.transform = "none";
            el.style.pointerEvents = "auto";
            el.classList.add("active", "visible");

            el.querySelectorAll('.reveal, .reveal-left, [class*="reveal"]').forEach(
              (child) => {
                const c = child as HTMLElement;
                c.style.opacity = "1";
                c.style.transform = "none";
                c.style.visibility = "visible";
                c.style.filter = "none";
                c.style.transition = "none";
                c.style.transitionDelay = "0s";
              },
            );
          } else {
            el.style.display = "none";
            el.classList.remove("active", "visible");
          }
        });
      }, i);

      await capturePage.waitForTimeout(300);
      const screenshot = await capturePage.screenshot({ fullPage: false });
      screenshots.push(screenshot);
    }

    await capturePage.close();

    // ── Step 2: Assemble screenshots into a PDF ─────────────────────
    const imagesHtml = screenshots
      .map((buf) => {
        const b64 = buf.toString("base64");
        return `<div class="page"><img src="data:image/png;base64,${b64}" /></div>`;
      })
      .join("\n");

    const pdfHtml = `<!DOCTYPE html>
<html><head><style>
  * { margin: 0; padding: 0; }
  @page { size: ${VP_WIDTH}px ${VP_HEIGHT}px; margin: 0; }
  .page { width: ${VP_WIDTH}px; height: ${VP_HEIGHT}px; page-break-after: always; overflow: hidden; }
  .page:last-child { page-break-after: auto; }
  img { width: ${VP_WIDTH}px; height: ${VP_HEIGHT}px; display: block; object-fit: contain; }
</style></head><body>${imagesHtml}</body></html>`;

    const pdfPage = await browser.newPage();
    await pdfPage.setContent(pdfHtml, { waitUntil: "load" });
    const pdfBytes = await pdfPage.pdf({
      width: `${VP_WIDTH}px`,
      height: `${VP_HEIGHT}px`,
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
    });
    await pdfPage.close();

    const filename = `COMERCIAL_${municipioSlug}.pdf`;

    return { pdfBuffer: Buffer.from(pdfBytes), filename };
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}
