import { configureFonts, MD3DarkTheme } from 'react-native-paper';
import { colors } from './colors';

export const syncTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primary,
    secondary: colors.statusPurple,
    background: colors.bgSecondary,
    surface: colors.bgElevated,
    surfaceVariant: colors.bgSurface,
    outline: colors.borderSubtle,
    outlineVariant: colors.borderMedium,
    onBackground: colors.textPrimary,
    onSurface: colors.textPrimary,
    onSurfaceVariant: colors.textSecondary,
    error: colors.statusError,
    onError: colors.textPrimary,
    inverseSurface: colors.bgSurface,
    inverseOnSurface: colors.textPrimary,
    inversePrimary: colors.primary,
    shadow: 'transparent',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.6)',
  },
  roundness: 8,
  fonts: configureFonts({
    config: {
      displayLarge: { fontFamily: 'System', fontSize: 57, lineHeight: 64, letterSpacing: -0.25, fontWeight: '400' },
      displayMedium: { fontFamily: 'System', fontSize: 45, lineHeight: 52, letterSpacing: 0, fontWeight: '400' },
      displaySmall: { fontFamily: 'System', fontSize: 36, lineHeight: 44, letterSpacing: 0, fontWeight: '400' },
      headlineLarge: { fontFamily: 'System', fontSize: 32, lineHeight: 40, letterSpacing: 0, fontWeight: '600' },
      headlineMedium: { fontFamily: 'System', fontSize: 28, lineHeight: 36, letterSpacing: 0, fontWeight: '600' },
      headlineSmall: { fontFamily: 'System', fontSize: 24, lineHeight: 32, letterSpacing: 0, fontWeight: '600' },
      titleLarge: { fontFamily: 'System', fontSize: 22, lineHeight: 28, letterSpacing: 0, fontWeight: '500' },
      titleMedium: { fontFamily: 'System', fontSize: 16, lineHeight: 24, letterSpacing: 0.15, fontWeight: '500' },
      titleSmall: { fontFamily: 'System', fontSize: 14, lineHeight: 20, letterSpacing: 0.1, fontWeight: '500' },
      bodyLarge: { fontFamily: 'System', fontSize: 16, lineHeight: 24, letterSpacing: 0.5, fontWeight: '400' },
      bodyMedium: { fontFamily: 'System', fontSize: 14, lineHeight: 20, letterSpacing: 0.25, fontWeight: '400' },
      bodySmall: { fontFamily: 'System', fontSize: 12, lineHeight: 16, letterSpacing: 0.4, fontWeight: '400' },
      labelLarge: { fontFamily: 'System', fontSize: 14, lineHeight: 20, letterSpacing: 0.1, fontWeight: '500' },
      labelMedium: { fontFamily: 'System', fontSize: 12, lineHeight: 16, letterSpacing: 0.5, fontWeight: '500' },
      labelSmall: { fontFamily: 'System', fontSize: 11, lineHeight: 16, letterSpacing: 0.5, fontWeight: '500' },
    },
  }),
};
